In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path("../../..").resolve()))

import pandas as pd
from src.utils.db import get_connection

conn = get_connection()

games_df = pd.read_sql(
    "SELECT * FROM steam_indie_games",
    conn
)

reviews_df = pd.read_sql(
    "SELECT * FROM steam_indie_reviews",
    conn
)

summary_df = pd.read_sql(
    "SELECT * FROM steam_indie_review_summary",
    conn
)

histogram_df = pd.read_sql(
    "SELECT * FROM steam_indie_review_histogram",
    conn
)

conn.close()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18784\2074152488.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  games_df = pd.read_sql(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18784\2074152488.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  reviews_df = pd.read_sql(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18784\2074152488.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  summary_df = pd.read_sql(
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_18784\2074152488.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  histogram_df = pd.read_sql(

In [2]:
games_df.shape

(9692, 14)

In [25]:
reviews_df.shape

(236379, 21)

In [28]:
summary_df.shape

(200, 7)

In [3]:
summary_list = summary_df['appid'].to_list()
reviews_list = reviews_df['appid'].unique().tolist()

In [4]:
diff_a = list(set(summary_list) - set(reviews_list))
diff_a

[2837370, 1818590, 2716270]

In [5]:
games_df[games_df['appid'].isin(diff_a)]

,appid,owners,positive,negative,price,ccu,genres,release_date,developers,total_reviews,owners_lower,is_f2p,is_early_access,name
4002,2716270,"0 .. 20,000",18,2,0,0,"['Casual', 'Indie', 'Simulation']",2023-12-22,Harvey games,20,0,False,False,The Witch's Cauldron Prologue
7371,1818590,"0 .. 20,000",51,29,99,0,"['Action', 'Adventure', 'Indie', 'Racing']",2024-01-06,GUNTER GAMES,80,0,False,False,You Are A Pilot
9391,2837370,"0 .. 20,000",10,7,399,0,"['Action', 'Indie']",2024-02-27,StarSystemStudios,17,0,False,False,NeverGoingHome

In [5]:
reviews_df[reviews_df['appid'].isin(diff_a)]

Empty DataFrame
Columns: [recommendationid, appid, language, review, timestamp_created, timestamp_updated, voted_up, votes_up, votes_funny, weighted_vote_score, comment_count, steam_purchase, received_for_free, written_during_early_access, author_steamid, author_num_games_owned, author_num_reviews, author_playtime_forever, author_playtime_last_two_weeks, author_playtime_at_review, author_last_played]
Index: []

[0 rows x 21 columns]

In [ ]:
games_df['total_reviews'] = games_df['total_reviews'].

0       110623
1       370046
2          322
3       253546
4        30805
         ...
9687        12
9688        14
9689        14
9690        13
9691        36
Name: total_reviews, Length: 9692, dtype: str

In [13]:
#games_df['is_f2p'] = games_df['is_f2p'].str.lower().replace({'true' : True, 'false' : False})
#games_df['is_early_access'] = games_df['is_early_access'].str.lower().replace({'true' : True, 'false' : False})
games_df['is_early_access'].value_counts()

is_early_access
False    9692
Name: count, dtype: int64

In [9]:
reviews_df['review']

0         幸存者玩法的游戏，本身属于手游转单机，最大的亮点在于其精致的卡通风格作画，各个可选角色都堪称...
1         并不推荐，这游戏有些怪外表令人看起来有点恶心（仅个人），并且后期有点难玩，我从第一关到第四关...
2         1. 武器重塑：玩法创新的灵魂\n单武器多路线进化：单武器可装 6 个同色 Buff，集齐 ...
3         Единственное что есть в этой игре - это прикол...
4         Fun fact, if you wanted to 100% this game, at ...
                                ...
236374                  ...Supreme!!\nThe wait was worth it
236375    我这人很少给差评，但是这游戏少有的把我玩到了红温状态，所以给了个向下的大拇指。\n游戏的机制...
236376    Simple premise, but excellent game for those w...
236377    Loved the first and love this game, too! Great...
236378    \n37小时 全成就通关：\n8个成就，最后四个成就的完成率都是0.1%，第四个成就完成率3...
Name: review, Length: 236379, dtype: str